# Generated by Django 2.2 on 2019-11-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srollno', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('smarks', models.FloatField()),
                ('saddr', models.TextField()),
            ],
        ),
    ]
