# Generated by Django 2.2.2 on 2020-02-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=258)),
                ('taste', models.CharField(max_length=258)),
                ('color', models.CharField(max_length=258)),
                ('price', models.FloatField()),
            ],
        ),
    ]
