# Generated by Django 2.2.7 on 2019-12-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
