# Generated by Django 2.2.7 on 2020-01-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_post_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_confirm_password',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='user_password',
            field=models.CharField(default=2, max_length=36),
            preserve_default=False,
        ),
    ]
