# Generated by Django 3.0.1 on 2019-12-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postapp', '0001_initial'),
        ('commentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentforpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.Post'),
        ),
    ]
