# Generated by Django 3.0.1 on 2019-12-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.TextField()),
                ('tagsforpost', models.ManyToManyField(to='postapp.Post')),
            ],
        ),
    ]
