# Generated by Django 2.2.4 on 2020-01-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bno', models.IntegerField()),
                ('max_strength', models.IntegerField(default=20)),
                ('available_strength', models.IntegerField()),
                ('date_from', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('fees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Studymaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('file', models.FileField(upload_to='document', verbose_name='file')),
                ('mcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suname', models.CharField(max_length=10, unique=True)),
                ('sname', models.CharField(max_length=10)),
                ('spassword', models.CharField(max_length=10)),
                ('saddress', models.CharField(max_length=10)),
                ('semail', models.EmailField(max_length=254)),
                ('snumber', models.IntegerField()),
                ('sbatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('fnumber', models.IntegerField()),
                ('fmail', models.EmailField(max_length=254)),
                ('fcourse', models.ManyToManyField(to='appone.Course')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='bcourse',
            field=models.ManyToManyField(to='appone.Faculty'),
        ),
    ]
