# Generated by Django 2.2.4 on 2020-01-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='bcourse',
            field=models.ManyToManyField(to='appone.Course'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
    ]
