# Generated by Django 2.2 on 2019-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_auto_20191211_1724'),
        ('Firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='civiljobs',
            name='user_civil',
            field=models.ManyToManyField(to='Userapp.UserReg'),
        ),
        migrations.AddField(
            model_name='itjobs',
            name='user_it',
            field=models.ManyToManyField(to='Userapp.UserReg'),
        ),
        migrations.AddField(
            model_name='mechjobs',
            name='user_mech',
            field=models.ManyToManyField(to='Userapp.UserReg'),
        ),
    ]
