# Generated by Django 2.2.4 on 2020-02-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itjobs',
            old_name='job_position',
            new_name='job_positionn',
        ),
    ]
