# Generated by Django 2.2.4 on 2020-02-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Firstapp', '0005_auto_20200224_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
