# Generated by Django 2.2 on 2019-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('tags', models.TextField()),
            ],
        ),
    ]
