# Generated by Django 2.2.7 on 2020-01-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinformation',
            name='productinformation_baseprice',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
