# Generated by Django 2.2.7 on 2020-01-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctiondetails',
            name='auctiondetails_baseprice',
        ),
    ]
