# Generated by Django 2.2.7 on 2020-01-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_remove_auctiondetails_auctiondetails_baseprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentbid',
            name='currentbid_bidderprice',
        ),
    ]
