# Generated by Django 2.2.4 on 2020-03-02 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('ecom', models.CharField(max_length=30)),
                ('esal', models.FloatField()),
                ('eaddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=30)),
                ('employee', models.ManyToManyField(to='firstapp.Employee')),
            ],
        ),
    ]
